void *AllocateFile (char file_name[], size_t &size);
void strcat (char destiny[], char add[]);
char *FilePath (char prefix[], char filename[], char suffix[]);
void Error (char string[]);
void CheckChartIntegrity (FILE *chartfile, char CheckString[]);
void sfscanf (FILE *file, char CheckString[]);
int min(int a, int b);
double min(double a, double b);
int max(int a, int b);
double max(double a, double b);
double Lanczos(double x, int Radius);
